### ISSUE TITLE
Calvin Evaluation log

### ISSUE THREAD

**Issue by haonan-duan** [TencentARC/Moto#1]
Hello, thanks for sharing your amazing project! I am wondering if you could share the evaluation log of Calvin simulation on ABC-D dataset. Thank you!

**Comment by ChenYi99** [comment]
Hi, thanks for your interest in our work! Attached are the evaluation log files for the Calvin simulation:
[result.txt](https://github.com/user-attachments/files/18057336/result.txt)
[success_rate.txt](https://github.com/user-attachments/files/18057338/success_rate.txt)

**Comment by haonan-duan** [comment]
> Hi, thanks for your interest in our work! Attached are the evaluation log files for the Calvin simulation: [result.txt](https://github.com/user-attachments/files/18057336/result.txt) [success_rate.txt](https://github.com/user-attachments/files/18057338/success_rate.txt)

Thanks for your sharing! BTW, did you find any "push_xxx_block_right" task has low success rate (xxx could be any color). And I find such results remain identical in many popular work, like your project, GR-1 and any others. I am confused why push right could be much worse than the same task towards opposite direction (push...left).

**Comment by ChenYi99** [comment]
Thank you for pointing out this issue. I also find it puzzling and am unsure why "push_xxx_block_right" tasks have a lower success rate.
