### ISSUE TITLE
missing relevant citation of LAPO and DynaMo

### ISSUE THREAD

**Issue by Howuhh** [TencentARC/Moto#3]
Hi! Insane work! 

Just wanted to say that I think two extremely relevant works are worth mentioning in related work:
1. Learning to act without actions, https://arxiv.org/abs/2312.10812, by @schmidtdominik
2. DynaMo: In-Domain Dynamics Pretraining for Visuo-Motor Control, https://arxiv.org/abs/2409.12192, by @jeffacce

**Comment by ChenYi99** [comment]
Thank you for the suggestions. We will add the relevant citations in the next version of our paper.
